export const DUMMY_TRADE = [
  {
    apt: "래미안퍼스티지",
    dong: "반포동",
    gu: "서초구",
    price: 680000,
    area: 165.26,
    floor: 22,
    date: "2026-03-14",
    newHigh: true,
  },
  {
    apt: "아크로리버파크",
    dong: "반포동",
    gu: "서초구",
    price: 745000,
    area: 172.4,
    floor: 18,
    date: "2026-03-14",
    newHigh: true,
  },
  {
    apt: "타워팰리스",
    dong: "도곡동",
    gu: "강남구",
    price: 320000,
    area: 132.7,
    floor: 35,
    date: "2026-03-13",
    newHigh: false,
  },
  {
    apt: "삼성동아이파크",
    dong: "삼성동",
    gu: "강남구",
    price: 410000,
    area: 148.2,
    floor: 12,
    date: "2026-03-13",
    newHigh: true,
  },
  {
    apt: "헬리오시티",
    dong: "가락동",
    gu: "송파구",
    price: 175000,
    area: 84.9,
    floor: 9,
    date: "2026-03-13",
    newHigh: false,
  },
  {
    apt: "파크리오",
    dong: "신천동",
    gu: "송파구",
    price: 195000,
    area: 101.9,
    floor: 14,
    date: "2026-03-12",
    newHigh: false,
  },
  {
    apt: "롯데캐슬파인힐",
    dong: "합정동",
    gu: "마포구",
    price: 128000,
    area: 84.5,
    floor: 7,
    date: "2026-03-12",
    newHigh: false,
  },
  {
    apt: "마포래미안푸르지오",
    dong: "아현동",
    gu: "마포구",
    price: 147000,
    area: 84.9,
    floor: 11,
    date: "2026-03-11",
    newHigh: true,
  },
  {
    apt: "왕십리센트라스",
    dong: "하왕십리동",
    gu: "성동구",
    price: 135000,
    area: 84.97,
    floor: 16,
    date: "2026-03-11",
    newHigh: false,
  },
  {
    apt: "서울숲리버뷰자이",
    dong: "성수동",
    gu: "성동구",
    price: 195000,
    area: 101.1,
    floor: 8,
    date: "2026-03-10",
    newHigh: true,
  },
  {
    apt: "한남더힐",
    dong: "한남동",
    gu: "용산구",
    price: 500000,
    area: 235.3,
    floor: 5,
    date: "2026-03-10",
    newHigh: false,
  },
  {
    apt: "나인원한남",
    dong: "한남동",
    gu: "용산구",
    price: 620000,
    area: 206.9,
    floor: 9,
    date: "2026-03-09",
    newHigh: true,
  },
  {
    apt: "반포자이",
    dong: "반포동",
    gu: "서초구",
    price: 290000,
    area: 145.1,
    floor: 3,
    date: "2026-03-09",
    newHigh: false,
  },
  {
    apt: "도곡렉슬",
    dong: "도곡동",
    gu: "강남구",
    price: 250000,
    area: 121.1,
    floor: 21,
    date: "2026-03-08",
    newHigh: false,
  },
  {
    apt: "잠실엘스",
    dong: "잠실동",
    gu: "송파구",
    price: 215000,
    area: 119.9,
    floor: 6,
    date: "2026-03-08",
    newHigh: false,
  },
  {
    apt: "신반포자이",
    dong: "반포동",
    gu: "서초구",
    price: 310000,
    area: 139.5,
    floor: 17,
    date: "2026-03-07",
    newHigh: true,
  },
  {
    apt: "대치아이파크",
    dong: "대치동",
    gu: "강남구",
    price: 280000,
    area: 124.7,
    floor: 10,
    date: "2026-03-07",
    newHigh: false,
  },
  {
    apt: "목동하이페리온",
    dong: "목동",
    gu: "양천구",
    price: 95000,
    area: 84.9,
    floor: 28,
    date: "2026-03-06",
    newHigh: false,
  },
  {
    apt: "여의도자이",
    dong: "여의도동",
    gu: "영등포구",
    price: 158000,
    area: 101.9,
    floor: 13,
    date: "2026-03-06",
    newHigh: false,
  },
  {
    apt: "은마아파트",
    dong: "대치동",
    gu: "강남구",
    price: 185000,
    area: 84.43,
    floor: 2,
    date: "2026-03-05",
    newHigh: false,
  },
  {
    apt: "압구정현대",
    dong: "압구정동",
    gu: "강남구",
    price: 385000,
    area: 196.0,
    floor: 7,
    date: "2026-03-05",
    newHigh: true,
  },
  {
    apt: "경희궁자이",
    dong: "평동",
    gu: "종로구",
    price: 130000,
    area: 84.9,
    floor: 15,
    date: "2026-03-04",
    newHigh: false,
  },
  {
    apt: "광교아이파크",
    dong: "이의동",
    gu: "수원시",
    price: 72000,
    area: 84.9,
    floor: 5,
    date: "2026-03-04",
    newHigh: false,
  },
  {
    apt: "판교푸르지오",
    dong: "백현동",
    gu: "성남시",
    price: 115000,
    area: 95.7,
    floor: 11,
    date: "2026-03-03",
    newHigh: false,
  },
];

export const DUMMY_RENT = [
  {
    apt: "래미안퍼스티지",
    dong: "반포동",
    gu: "서초구",
    deposit: 180000,
    monthly: 0,
    area: 165.26,
    floor: 15,
    date: "2026-03-14",
    type: "전세",
  },
  {
    apt: "헬리오시티",
    dong: "가락동",
    gu: "송파구",
    deposit: 80000,
    monthly: 0,
    area: 84.9,
    floor: 7,
    date: "2026-03-13",
    type: "전세",
  },
  {
    apt: "마포래미안푸르지오",
    dong: "아현동",
    gu: "마포구",
    deposit: 10000,
    monthly: 180,
    area: 84.9,
    floor: 9,
    date: "2026-03-12",
    type: "월세",
  },
  {
    apt: "파크리오",
    dong: "신천동",
    gu: "송파구",
    deposit: 90000,
    monthly: 0,
    area: 101.9,
    floor: 12,
    date: "2026-03-12",
    type: "전세",
  },
  {
    apt: "왕십리센트라스",
    dong: "하왕십리동",
    gu: "성동구",
    deposit: 5000,
    monthly: 150,
    area: 84.97,
    floor: 8,
    date: "2026-03-11",
    type: "월세",
  },
  {
    apt: "반포자이",
    dong: "반포동",
    gu: "서초구",
    deposit: 120000,
    monthly: 0,
    area: 145.1,
    floor: 5,
    date: "2026-03-11",
    type: "전세",
  },
  {
    apt: "잠실엘스",
    dong: "잠실동",
    gu: "송파구",
    deposit: 85000,
    monthly: 0,
    area: 119.9,
    floor: 10,
    date: "2026-03-10",
    type: "전세",
  },
  {
    apt: "도곡렉슬",
    dong: "도곡동",
    gu: "강남구",
    deposit: 15000,
    monthly: 250,
    area: 121.1,
    floor: 18,
    date: "2026-03-09",
    type: "월세",
  },
  {
    apt: "목동하이페리온",
    dong: "목동",
    gu: "양천구",
    deposit: 50000,
    monthly: 0,
    area: 84.9,
    floor: 22,
    date: "2026-03-08",
    type: "전세",
  },
  {
    apt: "여의도자이",
    dong: "여의도동",
    gu: "영등포구",
    deposit: 8000,
    monthly: 170,
    area: 101.9,
    floor: 9,
    date: "2026-03-07",
    type: "월세",
  },
  {
    apt: "경희궁자이",
    dong: "평동",
    gu: "종로구",
    deposit: 60000,
    monthly: 0,
    area: 84.9,
    floor: 12,
    date: "2026-03-06",
    type: "전세",
  },
  {
    apt: "은마아파트",
    dong: "대치동",
    gu: "강남구",
    deposit: 75000,
    monthly: 0,
    area: 84.43,
    floor: 4,
    date: "2026-03-05",
    type: "전세",
  },
];

export const TRADE_API = {
  apt: "apt-trade",
  offi: "offi-trade",
  villa: "villa-trade",
  house: "house-trade",
};
export const RENT_API = {
  apt: "apt-rent",
  offi: "offi-rent",
  villa: "villa-rent",
  house: "house-rent",
};

export const TRADE_COLS = [
  { key: "apt", label: "단지명", sortable: true, filterable: true },
  { key: "gu", label: "구/군", sortable: true, filterable: true },
  { key: "price", label: "거래가", sortable: true },
  { key: "newHigh", label: "전고가比", filterable: true },
  { key: "area", label: "면적", sortable: true },
  { key: "floor", label: "층", sortable: true },
  { key: "households", label: "세대수", sortable: true },
  { key: "completionYearMonth", label: "준공년월", sortable: true },
  { key: "nearbyStation", label: "근처 역" },
  { key: "date", label: "거래일", sortable: true },
  { key: "building", label: "건축물" },
];
export const RENT_COLS = [
  { key: "apt", label: "단지명", sortable: true, filterable: true },
  { key: "gu", label: "구/군", sortable: true, filterable: true },
  { key: "type", label: "유형", filterable: true },
  { key: "deposit", label: "보증금", sortable: true },
  { key: "monthly", label: "월세", sortable: true },
  { key: "area", label: "면적", sortable: true },
  { key: "floor", label: "층", sortable: true },
  { key: "date", label: "거래일", sortable: true },
];
export const LISTING_COLS = [
  { key: "apt", label: "단지명", sortable: true, filterable: true },
  {
    key: "completionYear",
    label: "준공년도",
    sortable: true,
    filterable: true,
  },
  { key: "zoning", label: "용도지역", sortable: true, filterable: true },
  {
    key: "legalFarLimit",
    label: "법정 상한",
    sortable: true,
    filterable: true,
  },
  {
    key: "currentFar",
    label: "현재 용적률",
    sortable: true,
    filterable: true,
  },
  {
    key: "siteArea",
    label: "대지면적",
    sortable: true,
    filterable: true,
  },
  {
    key: "households",
    label: "세대수",
    sortable: true,
    filterable: true,
  },
  {
    key: "nearbyStation",
    label: "근처 역",
    sortable: false,
    filterable: false,
  },
  {
    key: "flatLandStatus",
    label: "평지 추정",
    sortable: false,
    filterable: false,
  },
  {
    key: "nearbyElementarySchool",
    label: "초등학교(10분)",
    sortable: false,
    filterable: false,
  },
  {
    key: "nearbyPark",
    label: "공원(10분)",
    sortable: false,
    filterable: false,
  },
  {
    key: "landPerHousehold",
    label: "세대당 대지면적",
    sortable: true,
    filterable: true,
  },
  {
    key: "expectedUnits",
    label: "예상 신축 세대",
    sortable: true,
    filterable: true,
  },
  {
    key: "generalSaleUnits",
    label: "일반 분양분",
    sortable: true,
    filterable: true,
  },
  {
    key: "feasibility",
    label: "사업성 판단",
    sortable: true,
    filterable: true,
  },
];

export const BROKER_COLS = [
  { key: "companyName", label: "상호명", sortable: true, filterable: true },
  { key: "representativeName", label: "대표", sortable: true },
  { key: "dong", label: "동", sortable: true, filterable: true },
  { key: "businessYears", label: "영업연차", sortable: true },
  { key: "adminAction", label: "행정처분", filterable: true },
  { key: "tel", label: "연락처" },
  { key: "trustBadge", label: "신뢰도", sortable: true },
];

export const BROKER_PAGE_SIZE = 20;

export const PAGE_SIZE = 25;
export const LISTING_PAGE_SIZE = 20;
export const TREND_COLORS = [
  "#4f7cff",
  "#f5c842",
  "#ff4f6a",
  "#2ecc71",
  "#7c4fff",
  "#ff9f43",
];
export const TREND_LOOKBACK_MONTHS = 6;
export const TREND_SUGGEST_MONTHS = 12;
export const TREND_SUGGEST_PAGE_SIZE = 1000;
export const TREND_SUGGEST_MAX_PAGES = 3;
export const TREND_SUGGEST_DEFAULT_LIMIT = 30;
export const TREND_SUGGEST_SEARCH_LIMIT = 50;

export const state = {
  // Constants accessible as state.X for convenience
  TRADE_COLS,
  RENT_COLS,
  LISTING_COLS,
  BROKER_COLS,
  PAGE_SIZE,
  BROKER_PAGE_SIZE,
  LISTING_PAGE_SIZE,
  TREND_COLORS,
  TREND_LOOKBACK_MONTHS,
  TREND_SUGGEST_MONTHS,
  TREND_SUGGEST_PAGE_SIZE,
  TREND_SUGGEST_MAX_PAGES,
  TREND_SUGGEST_DEFAULT_LIMIT,
  TREND_SUGGEST_SEARCH_LIMIT,

  allData: [],
  rentData: [],
  currentPage: 1,
  rentPage: 1,
  sortKey: null,
  sortDir: "asc",
  rentSortKey: null,
  rentSortDir: "asc",
  colFilters: {},
  rentColFilters: {},
  cond: "all",
  rentTypeFilter: "all",
  propertyType: "apt",
  rentPropertyType: "apt",
  tradeStateMessage: "조회 버튼을 눌러주세요",
  rentStateMessage: "조회 버튼을 눌러주세요",
  localDatasetStatus: {
    stationsAvailable: false,
    apartmentCoordsAvailable: false,
  },
  listingData: [],
  listingPage: 1,
  listingSortKey: "generalSaleUnits",
  listingSortDir: "desc",
  listingColFilters: {},
  listingStateMessage:
    "사업성 분석 데이터를 불러오려면 조회를 눌러주세요",
  listingLoaded: false,
  listingLoading: false,
  listingSummaryData: null,
  listingRequestSeq: 0,
  listingLocationRequestKey: "",
  listingLocationInFlightIds: new Set(),
  listingLocationHydrationSeq: 0,
  trendApts: [],
  trendSelectionSeq: 0,
  trendData: {},
  trendSeriesSource: {},
  trendSuggestCache: {},
  trendSuggestResults: [],
  trendSuggestOpen: false,
  trendSuggestLoading: false,
  trendSuggestError: "",
  trendSuggestActiveIndex: -1,
  trendSuggestRequestToken: 0,

  // Broker tab
  brokerData: [],
  brokerDongs: [],
  brokerSummary: null,
  brokerSort: "trust",
  brokerGu: "",
  brokerDong: "",
  brokerPage: 1,
  brokerTotalCount: 0,
  brokerLoaded: false,
  brokerLoading: false,
  brokerStateMessage: "자치구를 선택하고 검색해주세요",
};
